const y=document.getElementById('y');if(y)y.textContent=new Date().getFullYear();
const intro=document.getElementById('intro');const enterBtn=document.getElementById('enterBtn');
enterBtn&&enterBtn.addEventListener('click',()=>{intro.classList.add('hidden')});
const sidebar=document.getElementById('sidebar');const openBtn=document.getElementById('openSidebar');const closeBtn=document.getElementById('closeSidebar');
openBtn&&openBtn.addEventListener('click',()=>sidebar.classList.add('open'));
closeBtn&&closeBtn.addEventListener('click',()=>sidebar.classList.remove('open'));
document.querySelectorAll('.nav-link').forEach(a=>a.addEventListener('click',()=>sidebar.classList.remove('open')));
const obs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')})},{threshold:.18});
document.querySelectorAll('.observe').forEach(el=>obs.observe(el));
const q=document.getElementById('q');const grid=document.getElementById('grid');q&&q.addEventListener('input',e=>{const t=e.target.value.toLowerCase();grid.querySelectorAll('.card').forEach(c=>{const v=(c.textContent+' '+(c.dataset.tags||'')).toLowerCase();c.style.display=v.includes(t)?'':'none'})});
