const PRODUCTS=[{id:'police-job',title:'Police Job Pro',price:49,description:'Complete police system with onboarding, fines, duty schedules.',features:['ESX/QBCore','Ranks','Optimized','Docs'],image:'https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1600&auto=format&fit=crop',labels:['Top','New']},{id:'billing',title:'Billing & Invoices',price:29,description:'Invoices, payment history, taxes, CSV export.',features:['Webhooks','API keys','Roles','Audit logs'],image:'https://images.unsplash.com/photo-1526378722484-bd91ca387e72?q=80&w=1600&auto=format&fit=crop',labels:['Popular']},{id:'garage-plus',title:'Garage+ Vehicles',price:35,description:'Garages, keys, insurance, impound.',features:['VIN system','Insurance','Anti-dupe','Perf profile'],image:'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1600&auto=format&fit=crop',labels:['Updated']}];const productGrid=document.getElementById('productGrid');const browseGrid=document.getElementById('browseGrid');const search=document.getElementById('search');const search2=document.getElementById('search2');const noResults=document.getElementById('noResults');function cardHTML(p){const labels=(p.labels||[]).map(l=>`<span class="badge">${l}</span>`).join(' ');const feats=(p.features||[]).map(f=>`<li>${f}</li>`).join('');return `<div class="card product" data-animate="fade-up">
    <img src="${p.image}" alt="${p.title}" />
    <div style="display:flex;justify-content:space-between;align-items:center;margin-top:10px">
      <h3 style="margin:0">${p.title}</h3>
      <div class="price">$${p.price}</div>
    </div>
    <p class="muted" style="margin:8px 0">${p.description}</p>
    <div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px">${labels}</div>
    <ul class="muted" style="margin-top:8px;padding-left:18px">${feats}</ul>
    <p class="xs muted" style="margin-top:8px">Buy flow disabled for now.</p>
  </div>`}function render(list,into){into.innerHTML=list.map(cardHTML).join('');observeAnimations()}render(PRODUCTS,productGrid);render(PRODUCTS,browseGrid);function filter(term){const t=term.trim().toLowerCase();const res=PRODUCTS.filter(p=>(p.title+p.description+(p.features||[]).join(' ')).toLowerCase().includes(t));render(res,browseGrid);noResults.style.display=res.length?'none':'block'}search?.addEventListener('input',e=>filter(e.target.value));search2?.addEventListener('input',e=>filter(e.target.value));let observer;function observeAnimations(){if(observer)observer.disconnect();observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');observer.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('[data-animate]').forEach(el=>observer.observe(el))}observeAnimations();const hamburger=document.getElementById('hamburger');const mobile=document.getElementById('mobileMenu');hamburger?.addEventListener('click',()=>{mobile.style.display=mobile.style.display==='flex'?'none':'flex'});document.getElementById('y').textContent=new Date().getFullYear();